version: '3.6'

services:
    app:
        build:
            context: ./
            dockerfile: app/Dockerfile
        ports:
            - 8899:8899
            - 6006:6006
            - 8080:8080
        volumes:
            - ./app/:/app/
        tty: true
        container_name: selfplay
        cap_add:
            - SYS_PTRACE
        deploy:
          resources:
            reservations:
              devices:
                - driver: nvidia
                  count: 1
                  capabilities: [gpu]

